### ISSUE TITLE
Release to central

### ISSUE THREAD

**Issue by uweschaefer** [brcolow/codeartifact-maven-extension#2]
Hi,

thanks for this useful extension. Indeed, it'd be super useful to be able to grab this from central (so that we can avoid problems in the area of chicken and eggs).

**Comment by brcolow** [comment]
I agree. I will look into that.

Note to self:

The old JIRA ticket system for making Maven central repos is deprecated and the new system has a auto-verify feature when using Github logins. We have io.github.brcolow namespace, just need to configure `mvn deploy` plugin now (https://central.sonatype.org/publish/publish-maven/). See also [token generation](https://central.sonatype.org/publish/generate-token/).

**Comment by brcolow** [comment]
I am currently working on this. Getting held up by a 401 unauthorized error from `nexus-staging-maven-plugin`.

**Comment by brcolow** [comment]
This has been [released to central](https://central.sonatype.com/artifact/io.github.brcolow/codeartifact-maven-extension). Thank you.
